Feature/fetch contacts from phone
MrrMurzik/messengerAndroid pull request #6
Opened 2023-02-22 17:32 UTC by MrrMurzik

MA-5: when app starts first time, by clicking on the button "My Contacts" in "MyProfileActivity", appears "MyContactActivity" with a list of hardcoded users, and shows up standard system dialog with requesting permission for fetching contacts. I want that system dialog appear before creating of activity

2023-02-26 10:40 UTC, 1937Carrie commented
![photo_2023-02-26_12-29-37](https://user-images.githubusercontent.com/49805850/221405531-e3ec70cf-be29-4374-bdad-96fa8fd498cc.jpg)
![photo_2023-02-26_12-29-37 (2)](https://user-images.githubusercontent.com/49805850/221405529-91c8f327-bd30-47fb-953c-6bf3638798ea.jpg)

2023-02-26 11:11 UTC, 1937Carrie requested changes
Describe in detail in the discord what you want to ask about permissions.

2023-02-26 11:11 UTC, 1937Carrie commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/MyContactsActivity.kt
> +    private val viewModel: ContactsViewModel by viewModels {
May be you should better initialize viewmodel in one of this approach https://stackoverflow.com/a/54313573/20937549 or can try https://github.com/MrrMurzik/messengerAndroid/pull/6#issuecomment-1445324380.

2023-02-26 11:11 UTC, 1937Carrie commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/MyContactsActivity.kt
> +    fun fetchContacts(): MutableList<User> {
Should move the fetching of contacts to another class.

2023-02-26 11:11 UTC, 1937Carrie commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/MyContactsActivity.kt
> +                if (grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
Call of methods in if statement and else statement is the same.

2023-02-26 11:11 UTC, 1937Carrie commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/MyContactsActivity.kt
> +        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
Usually the call to the super is written at the beginning.

2023-02-26 11:11 UTC, 1937Carrie commented on app/src/main/java/com/example/messengerAndroid/ui/myProfile/MyProfileActivity.kt
> +            intent.putExtra("Fetching key", isFetchedContact)
Should extract the literal into constants.

2023-02-28 18:04 UTC, MrrMurzik commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/MyContactsActivity.kt
> +    private val viewModel: ContactsViewModel by viewModels {
Why do you think my approach is bad?

2023-02-28 19:26 UTC, EugeneOrlov204 commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/MyContactsActivity.kt
> +    private val viewModel: ContactsViewModel by viewModels {
Why did you remove by viewModels in the first place? As for me it is the best choice to initialize a view model

2023-03-01 12:31 UTC, EugeneOrlov204 commented on app/src/main/java/com/example/messengerAndroid/ui/customView/DismissableKeyboardConstraintLayout.kt
> +}
fun View.hideKeyboard() {
    val inputMethodManager =
        context.getSystemService(android.app.Activity.INPUT_METHOD_SERVICE) as InputMethodManager
    inputMethodManager.hideSoftInputFromWindow(windowToken, 0)
}

2023-03-01 12:41 UTC, EugeneOrlov204 commented on app/src/main/res/layout/activity_my_profile.xml
> +        android:layout_marginBottom="10dp"
hardcoded

2023-03-01 12:43 UTC, EugeneOrlov204 approved these changes

2023-03-01 15:33 UTC, MrrMurzik commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/MyContactsActivity.kt
> +    private val viewModel: ContactsViewModel by viewModels {
We have already discussed it with Eugene, I did not delete by viewModels, just add factory for viewModel to pass there arguments

2023-03-01 18:33 UTC, 1937Carrie approved these changes
My review is directed at not-so-convincing places of code that can throw exceptions in specific situations. In general, the code is normal.

2023-03-01 18:33 UTC, 1937Carrie commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/contactsViewModel/factory/ContactsViewModelFactory.kt
> +@Suppress("UNCHECKED_CAST")
Annotation of suppress should be removed

2023-03-01 18:33 UTC, 1937Carrie commented on app/src/main/java/com/example/messengerAndroid/ui/myContacts/ContactFetcher.kt
> +                    it.getLong(it.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.CONTACT_ID))
"or Throw" doesn't look confident

2023-03-02 12:40 UTC, merged